### PR TITLE
Fetch frontend

### PR DESCRIPTION
**Pull request by jeffreypliang**
I changed the fetch UI so that it's more consistent with the rest of the website, though I don't really know how I feel about it. As is, the text updates before the animation is complete, and there are some other weird animation behaviors, but I think I know how to fix them once the voting stuff works.

### CODE REVIEW

**Comment by ben9583** [comment]
Idk, I think it's a bit too much. It kinda gets rid of the blue color we had as a theme, and when the thought is only one line, it's difficult to read cause the colors clash. Also, the upvotes and downvotes don't display. Do you think we could make it so the blue stays more dominant and find a way to integrate vote counts @jeffreypliang?

**Comment by ben9583** [comment]
Screen Shot 2019-10-28 at 4 19 02 PM
this is the design for reference

**Comment by jeffreypliang** [comment]
I don't think we should display the upvotes and downvotes partially because it makes it too like reddit but also because it's more simple without them and users aren't influenced by the numbers they see.

I kinda like the split-screen design (and I think Bianca said she liked it too), but the colors probably are too much. I was also thinking about putting big arrows (or some other icon) above and below the text, but you can still click anywhere on the top or bottom half to vote.

**Comment by ben9583** [comment]
That makes sense. I'll accept it but yea we should probably work on making the colors work more with the website so let's make that a task before we do the video.

**Review by ben9583 — APPROVED** [review]

**Comment by ben9583** [comment]
Also I do think we could look into fixing that split-screen issue with the text. just cause it does make it kinda hard to read.

**Pull request merged**
